import type {
  ComponentDefinition,
  ComponentId,
  Scenario,
  SimulationEvent,
} from "../domain/simulation";

const events: SimulationEvent[] = [
  {
    id: "python-backward",
    title: "Python enters loss.backward()",
    compactTitle: "Backward begins",
    start: 0,
    duration: 1.2,
    kind: "launch",
    layer: "framework",
    actor: "python",
    location: "CPU process",
    explanation:
      "Each rank enters the same training code with a different local batch.",
    details: [
      "The Python process owns one model replica.",
      "Autograd already recorded the operator dependency graph during forward.",
    ],
  },
  {
    id: "autograd-schedules",
    title: "Autograd schedules the linear backward node",
    compactTitle: "Autograd schedules",
    start: 1.2,
    duration: 1.2,
    kind: "launch",
    layer: "framework",
    actor: "autograd",
    location: "CPU process",
    dependencies: ["python-backward"],
    explanation:
      "The engine finds a ready backward node and prepares the inputs for dW = XᵀdY.",
    details: [
      "A CPU thread runs the host-side operator code.",
      "The thread submits work instead of calculating every gradient element itself.",
    ],
  },
  {
    id: "gradient-kernel",
    title: "CUDA executes the gradient kernel",
    compactTitle: "Gradient kernel",
    start: 2.4,
    duration: 2.2,
    kind: "compute",
    layer: "compute",
    actor: "sm",
    location: "GPU SMs",
    tensor: "weight.grad",
    source: "hbm",
    destination: "sm",
    dependencies: ["autograd-schedules"],
    explanation:
      "Thread Blocks land on SMs. Warp schedulers issue matrix instructions and accumulate gradient tiles.",
    details: [
      "A Block stays on one SM, while an SM may host several Blocks.",
      "A warp normally contains 32 CUDA threads on NVIDIA GPUs.",
      "Registers hold local accumulators and shared memory can stage reused tiles.",
    ],
  },
  {
    id: "gradient-writeback",
    title: "The gradient is written to HBM",
    compactTitle: "Gradient writeback",
    start: 4.6,
    duration: 1,
    kind: "write",
    layer: "memory",
    actor: "hbm",
    location: "GPU device memory",
    tensor: "weight.grad",
    source: "sm",
    destination: "hbm",
    dependencies: ["gradient-kernel"],
    explanation:
      "The completed values are stored in the memory region associated with parameter.grad.",
    details: [
      "L1 and L2 may cache accesses on the way to device memory.",
      "PyTorch keeps the shape and parameter-to-buffer mapping.",
    ],
  },
  {
    id: "bucket-ready",
    title: "DDP marks gradient bucket 0 ready",
    compactTitle: "Bucket ready",
    start: 5.6,
    duration: 1,
    kind: "ready",
    layer: "collective",
    actor: "ddp",
    location: "Rank-local GPU buffer",
    tensor: "bucket-0",
    source: "hbm",
    destination: "ddp",
    dependencies: ["gradient-writeback"],
    explanation:
      "A DDP hook observes that every gradient assigned to this bucket is ready.",
    details: [
      "Bucketing amortizes collective launch overhead.",
      "A CUDA Event prevents the communication stream from reading unfinished data.",
    ],
  },
  {
    id: "reduce-scatter-0",
    title: "Reduce-Scatter round 1",
    compactTitle: "Reduce-Scatter 1",
    start: 6.6,
    duration: 1.1,
    kind: "reduce-scatter",
    layer: "collective",
    actor: "nccl",
    location: "NCCL communication stream",
    tensor: "bucket-0 chunks",
    source: "gpu-0",
    destination: "gpu-1",
    dependencies: ["bucket-ready"],
    explanation:
      "Every rank sends a different chunk to its next ring neighbor and reduces the chunk it receives.",
    details: [
      "The link carries tensor values, not a remote virtual address.",
      "Rank and round determine the local send and receive chunk.",
    ],
  },
  {
    id: "reduce-scatter-1",
    title: "Reduce-Scatter round 2",
    compactTitle: "Reduce-Scatter 2",
    start: 7.7,
    duration: 1.1,
    kind: "reduce-scatter",
    layer: "collective",
    actor: "nccl",
    location: "NCCL communication stream",
    tensor: "partially reduced chunks",
    source: "gpu-1",
    destination: "gpu-2",
    dependencies: ["reduce-scatter-0"],
    explanation:
      "Chunks advance one hop. NCCL kernels add received values into local buffers.",
    details: [
      "Communication kernels also consume SM and memory bandwidth.",
      "NVLink transports bytes while GPU instructions perform local reduction work.",
    ],
  },
  {
    id: "reduce-scatter-2",
    title: "Reduce-Scatter round 3",
    compactTitle: "Reduce-Scatter 3",
    start: 8.8,
    duration: 1.1,
    kind: "reduce-scatter",
    layer: "collective",
    actor: "nccl",
    location: "NCCL communication stream",
    tensor: "reduced chunks",
    source: "gpu-2",
    destination: "gpu-3",
    dependencies: ["reduce-scatter-1"],
    explanation:
      "After N - 1 rounds, each rank owns one fully reduced chunk.",
    details: [
      "The result is distributed across ranks at this point.",
      "All-Gather will replicate these completed chunks.",
    ],
  },
  {
    id: "all-gather-0",
    title: "All-Gather round 1",
    compactTitle: "All-Gather 1",
    start: 9.9,
    duration: 0.9,
    kind: "all-gather",
    layer: "collective",
    actor: "nccl",
    location: "NVLink ring",
    tensor: "reduced chunks",
    source: "gpu-3",
    destination: "gpu-0",
    dependencies: ["reduce-scatter-2"],
    explanation:
      "Each rank forwards the completed chunk it currently owns.",
    details: [
      "No further arithmetic is required for an already reduced chunk.",
      "Ranks still follow the same collective order contract.",
    ],
  },
  {
    id: "all-gather-1",
    title: "All-Gather round 2",
    compactTitle: "All-Gather 2",
    start: 10.8,
    duration: 0.9,
    kind: "all-gather",
    layer: "collective",
    actor: "nccl",
    location: "NVLink ring",
    tensor: "reduced chunks",
    source: "gpu-0",
    destination: "gpu-1",
    dependencies: ["all-gather-0"],
    explanation:
      "Completed chunks continue around the ring until every rank has all of them.",
    details: [
      "The collective is deterministic from rank, round, and world size.",
      "There is no central controller issuing per-rank instructions each round.",
    ],
  },
  {
    id: "all-gather-2",
    title: "All-Gather round 3",
    compactTitle: "All-Gather 3",
    start: 11.7,
    duration: 0.9,
    kind: "all-gather",
    layer: "collective",
    actor: "nccl",
    location: "NVLink ring",
    tensor: "complete bucket-0",
    source: "gpu-1",
    destination: "gpu-2",
    dependencies: ["all-gather-1"],
    explanation:
      "Every rank now owns the same fully reduced gradient bucket.",
    details: [
      "DDP can divide by world size before or after the SUM collective.",
      "The final buffer represents the average gradient on every rank.",
    ],
  },
  {
    id: "bucket-writeback",
    title: "The synchronized bucket becomes parameter.grad",
    compactTitle: "Gradient visible",
    start: 12.6,
    duration: 1.2,
    kind: "synchronize",
    layer: "memory",
    actor: "ddp",
    location: "GPU HBM on every rank",
    tensor: "parameter.grad",
    source: "nccl",
    destination: "hbm",
    dependencies: ["all-gather-2"],
    explanation:
      "NCCL writes the result into the agreed buffer. PyTorch already knows how that buffer maps to parameters.",
    details: [
      "NCCL does not need to understand model layers or .grad.",
      "A gradient can be a view into the bucket or receive a framework-managed copy.",
    ],
  },
  {
    id: "optimizer-update",
    title: "Optimizer kernels update every model replica",
    compactTitle: "Optimizer update",
    start: 13.8,
    duration: 1.8,
    kind: "update",
    layer: "optimizer",
    actor: "optimizer",
    location: "GPU compute stream",
    tensor: "parameters and optimizer state",
    source: "hbm",
    destination: "hbm",
    dependencies: ["bucket-writeback"],
    explanation:
      "Each rank reads the same gradient and applies the same optimizer rule to its model replica.",
    details: [
      "AdamW reads parameters, gradients, exp_avg, and exp_avg_sq.",
      "CUDA threads update many parameter elements in parallel.",
      "Identical inputs produce identical model replicas for the next iteration.",
    ],
  },
  {
    id: "iteration-complete",
    title: "All ranks enter the next iteration",
    compactTitle: "Iteration complete",
    start: 15.6,
    duration: 1.4,
    kind: "write",
    layer: "framework",
    actor: "python",
    location: "Four synchronized ranks",
    tensor: "updated parameters",
    dependencies: ["optimizer-update"],
    explanation:
      "The ranks remain separate processes, but their model replicas now contain the same values.",
    details: [
      "Synchronization happens at state boundaries instead of every CPU instruction.",
      "The next forward pass can begin with a new local batch.",
    ],
  },
];

export const ddpScenario: Scenario = {
  id: "ddp-gradient-journey",
  title: "A gradient's journey through DDP",
  subtitle: "Backward, bucketization, Ring All-Reduce, and optimizer update",
  worldSize: 4,
  totalDuration: 17,
  events,
};

const rankDefinition = (id: ComponentId, rank: number): ComponentDefinition => ({
  id,
  name: `GPU ${rank}`,
  category: `rank ${rank}`,
  role: "Executes compute and communication kernels for one model replica.",
  knows: "CUDA work, device addresses, streams, and local memory.",
  doesNotKnow: "Why a tensor is semantically a model gradient.",
});

export const components: Record<ComponentId, ComponentDefinition> = {
  python: {
    id: "python",
    name: "Python rank process",
    category: "host software",
    role: "Runs the training program and owns one model replica.",
    knows: "The model, optimizer, local batch, and high-level training order.",
    doesNotKnow: "How individual GPU warps execute an instruction.",
  },
  autograd: {
    id: "autograd",
    name: "Autograd Engine",
    category: "framework",
    role: "Tracks dependencies and schedules ready backward operators.",
    knows: "The computation graph and gradient accumulation dependencies.",
    doesNotKnow: "The physical route used by an NVLink packet.",
  },
  cpu: {
    id: "cpu",
    name: "CPU",
    category: "host hardware",
    role: "Executes host threads that control and submit device work.",
    knows: "Process state, runtime calls, and control-flow decisions.",
    doesNotKnow: "The meaning of every byte transported by the device link.",
  },
  "gpu-0": rankDefinition("gpu-0", 0),
  "gpu-1": rankDefinition("gpu-1", 1),
  "gpu-2": rankDefinition("gpu-2", 2),
  "gpu-3": rankDefinition("gpu-3", 3),
  sm: {
    id: "sm",
    name: "Streaming Multiprocessor",
    category: "GPU execution",
    role: "Keeps many warps resident and issues ready instructions.",
    knows: "Warp state, registers, shared memory, and instruction dependencies.",
    doesNotKnow: "Python objects, model layer names, or optimizer semantics.",
  },
  hbm: {
    id: "hbm",
    name: "GPU HBM",
    category: "device memory",
    role: "Stores tensors, gradients, buckets, parameters, and optimizer state.",
    knows: "Addressable bytes and memory requests.",
    doesNotKnow: "Whether those bytes represent a gradient or a parameter.",
  },
  ddp: {
    id: "ddp",
    name: "DistributedDataParallel",
    category: "training semantics",
    role: "Determines which gradients become ready and when to synchronize them.",
    knows: "Parameters, gradients, bucket mappings, and synchronization points.",
    doesNotKnow: "Every low-level hop selected by the communication backend.",
  },
  nccl: {
    id: "nccl",
    name: "NCCL",
    category: "collective library",
    role: "Implements collectives over GPU buffers and the available topology.",
    knows: "Buffers, counts, dtypes, operations, ranks, and links.",
    doesNotKnow: "Model layer names, parameter.grad, or the loss function.",
  },
  nvlink: {
    id: "nvlink",
    name: "NVLink ring",
    category: "interconnect",
    role: "Moves tensor bytes between GPUs inside this illustrated node.",
    knows: "Packets, link endpoints, ordering, and transport state.",
    doesNotKnow: "Collective meaning or model semantics.",
  },
  optimizer: {
    id: "optimizer",
    name: "Optimizer",
    category: "training algorithm",
    role: "Consumes synchronized gradients and updates parameters and state.",
    knows: "Parameter groups, gradients, hyperparameters, and optimizer state.",
    doesNotKnow: "How NCCL split the bucket into ring chunks.",
  },
};
